workflows:
  ios-workflow:
    name: Build iOS IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "AnimoX.xcworkspace"
        XCODE_SCHEME: "AnimoX"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          pod install --repo-update
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs 'CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
    artifacts:
      - build/ios/ipa/*.ipa
